import { userService } from '../services';
import { useState, useEffect } from 'react';
import Link from 'next/link';
import Head from 'next/head'
import { useRouter } from 'next/router';
import styles from '../styles/Home.module.css';

export default function Home() {
  const router = useRouter()
  const [user, setUser] = useState<any>(null);

  useEffect(() => {
    setUser(userService.getUser())
  }, []);

  function logOut() {
    userService.logout();
    setUser(null);
    router.push('/account/login');
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div >
          <h1>Hi {user?.username} !</h1>
          <p>You&apos;re logged in with Next.js & JWT!!</p>
          {!user && <Link href="/account/login">Login</Link>}
          {user && <button onClick={logOut}>Logout</button>}
        </div>
      </main>
    </>
  )
}
